### PR TITLE
Add comment from 696696

### PR DESCRIPTION
**Pull request by staticmancommentbot**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field          | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| -------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| replying_to_id |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| name           | 696696                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| message        | Skip to content

    Product 

Team
Enterprise
Explore
Marketplace
Pricing

Sign in
Sign up
@gouravkhunger gouravkhunger
Overview
Repositories 42
Projects
Packages
Stars 40
@gouravkhunger gouravkhunger
Avatar
🎯
Focusing
Gourav Khunger gouravkhunger
16. Founder @genicsblog. Developing @jekyllex. Frontend engineer @SpeechKit (BeyondWords). Passionate App Developer.
74 followers · 18 following

@SpeechKit
At my desk
https://gouravkhunger.xyz

    @gourav_khunger 

Highlights

    Developer Program Member

Organizations
@code19-contest @RecycleAid @jekyllex @genicsblog
@cherryleafroad
Kobato cherryleafroad
I'm a software engineer who loves Rust, with experience in web technologies, app development, and some game design.

At my computer
@shockz09
Rohit Mishra shockz09
Hi there, I am Rohit Mishra a web developer and a student

Lucknow , Uttar Pradesh , India
@Posandu
Posandu Posandu
14. Founder of @Tronic247 And Tronic247 Material

@Tronic247

Tronic247
@Kira272921
Kira Kira272921
15, backend dev, exploring web3 🌈

India
@carrotfarmer
Dhruva Srinivas carrotfarmer
13-year-old backend programmer

bangalore
@srevinsaju
Srevin Saju srevinsaju
Google Code-In GPW 2019 @sugarlabs. Working on interesting and open source software, free for everyone @KDE @vector-im @AppImage

@sorcero

Bahrain
@max-programming
Max Programming max-programming
Student, Programmer, Youtuber. Learning Web Development

Indian
@avneesh0612
Avneesh Agarwal avneesh0612
A full-stack web developer, designer, content creator, opensource enthusiast and student 🤓

@YOKE-GAMING

India
@kr-anurag
Anurag kr-anurag
I'm a Frontend Engineer, a Blogger and a Student

India
@samdishakhunger
Samdisha Khunger samdishakhunger
@AnishDe12020
Anish De AnishDe12020
14 • Tech Enthusiast • Fullstack Web Developer • Blogger • Tech YouTuber

Earth
@Kardev07
Karthik Pariti Kardev07
I am a Web Developer and an AI engineer currently learning OS Development and deeply in love with Rust Lang

@relm-inc

Hyderabad, India
@TheBlapse
Badal Panchani TheBlapse

India
@aldrichalvarez
Aldrich Heinz Alvarez aldrichalvarez
Building @realmforteens and @healthdex-app 🚀 Working as an intern at @Blueberry-Markets 🫐

@realmforteens @healthdex-app @Blueberry-Markets

Caloocan City, NCR, Philippines
@aditya-singh9
Aditya Singh aditya-singh9
Hi, I'm Aditya, a self-motivated Tech Enthusiast and a Full Stack Web developer. (most work in private repos)

@GRAMOLY-ORG

India
@voidz7
voidz voidz7
High School idiot who likes Computer Science.
@Kushagra-Jain99
Kushagra Jain Kushagra-Jain99

@genicsblog

India

    © 2022 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About |
| date           | 1650360719                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

### CODE REVIEW

**Comment by max-programming** [comment]
What does this mean? @gouravkhunger

**Comment by carrotfarmer** [comment]
bruh

**Comment by gouravkhunger** [comment]
I am super sorry for the pings everyone go here :(

A person tried to spam comment on the articles. I have stopped the comments api for some time and seriously re-considering how comments work on the blog.

It turns out that the person pinged everyone whom I follow. It even passed recaptcha and akismet spam checks because its not done by a bot and links to text ratio is not marking it as spam.

I will close all the spam PRs. Once again I am super sorry to the people who got the pings. I'll make sure this won't happen again.

**Comment by Kira272921** [comment]
ayo wtf

**Pull request closed without merging**
